---
- hosts: localhost
  sudo: yes
  vars:
    home_dir: /home/vagrant/
    repos_dir: /home/vagrant/repos/git/
    log_dir: /home/vagrant/ansible/log/
    flg_dir: /home/vagrant/ansible/flg/
    user: vagrant
  tasks:
    - name: vimインストール
      yum: name=vim-enhanced state=installed

    - name: development_toolsインストール
      yum: name="@Development tools" state=installed

#    - name: apacheインストール
#      yum: name=httpd state=installed

    - name: libselinux-pythonインストール
      yum: name=libselinux-python state=installed

#    - name: apacheは停止しておく
#      service: name=httpd state=stopped enabled=no

    - name: gitインストール
      yum: name=git state=installed

    - name: openssl-develインストール
      yum: name=openssl-devel state=installed

    - name: sqliteインストール
      yum: name=sqlite state=installed

    - name: sqlite-develインストール
      yum: name=sqlite-devel state=installed

    - name: Python3のtarballをダウンロード
      get_url: url=https://www.python.org/ftp/python/3.4.3/Python-3.4.3.tar.xz dest=/tmp

    - name: Python3のtarballを展開
      unarchive: src=/tmp/Python-3.4.3.tar.xz dest=/usr/local/src

    - name: Python3をインストール
      shell: >
        ./configure --prefix=/usr/local &&
        make &&
        make altinstall
        chdir=/usr/local/src/Python-3.4.3
        creates=/usr/local/bin/python3.4

    - name: virtualenvをインストール
      pip: name=virtualenv executable=/usr/local/bin/pip3.4

    - name: virtualenvに入る・bottleインストール
      pip: name=bottle virtualenv=~vagrant/myenv virtualenv_command=/usr/local/bin/virtualenv-3.4
      sudo: no

    - name: sqlalchemyインストール
      pip: name=sqlalchemy virtualenv=~vagrant/myenv virtualenv_command=/usr/local/bin/virtualenv-3.4
      sudo: no

#    - name: bottleアプリケーション実行
#      shell: nohup ~/myenv/bin/python3.4  /vagrant/bottle/hello_world.py &
#      sudo: no
